### ISSUE TITLE
Bug: [1.20.1 Forge] Server tick timeout - EntityListener_onEntityJoin_EntityJoinLevelEvent

### ISSUE THREAD

**Issue by MrKashew** [Gilded-Games/The-Aether#1713]
### What Feature Types Apply to This Bug?

Entity, System, World-Gen

### What Type of Bug Is This?

Crash

### Forge Version

1.20.1

### The Aether Version

1.20.1-1.0.0-beta.1-neoforge

### Is This Bug a Conflict With Another Mod?

Maybe

### Crash Report (if applicable)

https://gist.github.com/MrKashew/ddb8f8f0c76389a59f6fcb1c921647a0

### Steps to Reproduce

1. Running server with the listed mods
2. Server ticking slows until a halt / timeout

### What You Expect To Happen

No tick timeout

### What Actually Happened

Tick timeout crash serverside - not generally happening before adding this mod to the pack

### Additional Details

Let me know if there is more I can provide or test!

```
"Server thread" prio=8 Id=94 TIMED_WAITING on java.lang.String@2d482945
	at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.lang.String@2d482945
	at java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_5667_(BlockableEventLoop.java:151)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:141)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:131)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_6522_(Level.java:187)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_6325_(Level.java:182)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46745_(Level.java:178)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_6436_(Level.java:862)
	at TRANSFORMER/aether@1.20.1-1.0.0-beta.1-neoforge/com.aetherteam.aether.event.hooks.EntityHooks.spawnWithAccessories(EntityHooks.java:107)
	at TRANSFORMER/aether@1.20.1-1.0.0-beta.1-neoforge/com.aetherteam.aether.event.listeners.EntityListener.onEntityJoin(EntityListener.java:47)
	at TRANSFORMER/aether@1.20.1-1.0.0-beta.1-neoforge/com.aetherteam.aether.event.listeners.__EntityListener_onEntityJoin_EntityJoinLevelEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus$$Lambda$4303/0x0000000801807cd8.invoke(Unknown Source)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:79)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157604_(PersistentEntitySectionManager.java:121)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.PersistentEntitySectionManager$$Lambda$50064/0x0000000805be5000.accept(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.EntityType$1.m_147060_(EntityType.java:585)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.EntityType$1$$Lambda$50066/0x0000000805be5460.apply(Unknown Source)
	at java.base@17.0.7/java.util.Optional.map(Optional.java:260)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.EntityType.m_20645_(EntityType.java:563)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.EntityType$1.m_147056_(EntityType.java:584)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.EntityType$1$$Lambda$50065/0x0000000805be5230.accept(Unknown Source)
	at java.base@17.0.7/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.EntityType$1.tryAdvance(EntityType.java:583)
	at java.base@17.0.7/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base@17.0.7/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157559_(PersistentEntitySectionManager.java:120)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_143327_(ServerLevel.java:1434)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.m_143064_(ChunkMap.java:690)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.m_214898_(ChunkMap.java:707)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap$$Lambda$48362/0x0000000805a2bd00.m_196866_(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk.m_62952_(LevelChunk.java:438)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.m_214854_(ChunkMap.java:715)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap$$Lambda$48361/0x0000000805a2b8c8.apply(Unknown Source)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either$$Lambda$47687/0x000000080597c318.apply(Unknown Source)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either.mapLeft(Either.java:162)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.m_287044_(ChunkMap.java:699)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap$$Lambda$48358/0x0000000805a2b248.apply(Unknown Source)
	at java.base@17.0.7/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base@17.0.7/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkTaskPriorityQueueSorter$$Lambda$47703/0x00000008059848d0.run(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:541)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:549)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:269)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer$$Lambda$47022/0x000000080583cb78.run(Unknown Source)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
```

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Alexmasonseals** [comment]
hm yeah. that seems like a pretty heavy modpack, i wouldn't be surprised if you ran into issues, i don't think we can fix this one unless you confirm that the server is stalling without any mod except the aether

**Comment by MrKashew** [comment]
thanks so much for this fix - tried on latest release and it works wonders, server is performing great tick wise now!
