### ISSUE TITLE
Bug: mobs crash

### ISSUE THREAD

**Issue by TioNickZeus** [Gilded-Games/The-Aether#1743]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

43.2.21

### The Aether Version

beta 1.1

### Is This Bug a Conflict With Another Mod?

probrably?

### Crash Report (if applicable)

https://gist.github.com/TioNickZeus/cb88e8b5ebdccf4395a828660fc63507

### Steps to Reproduce

it just happened one, cause i put a mod to "fix" it, but basically the mod kills the valkyries before they crash the server
1. enters aether
2. find a valkyrie
3. crash

### What You Expect To Happen

the server just crashad as soon as one of the players got hit by a valkyrie

### What Actually Happened

the server crashed

### Additional Details

[Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.world.entity.EquipmentSlot.equals(Object)" because the return value of "net.minecraftforge.event.ItemAttributeModifierEvent.getSlotType()" is null
[21.09 09:14:33] [Server] 	Index1
[21.09 09:14:33] [Server] 	Listeners:
[21.09 09:14:33] [Server] 		NORMAL
[21.09 09:14:33] [Server] 		ASM: com.cgessinger.creaturesandbeasts.events.CNBEvents@5ffd086 onItemAttributeModifierCalculate(Lnet/minecraftforge/event/ItemAttributeModifierEvent;)V
[21.09 09:14:33] [Server] 		ASM: class com.blamejared.crafttweaker.impl.event.CTCommonEventHandler attribute(Lnet/minecraftforge/event/ItemAttributeModifierEvent;)V
[21.09 09:14:33] [Server] 		ASM: class io.redspace.ironsspellbooks.player.ServerPlayerEvents handleUpgradeModifiers(Lnet/minecraftforge/event/ItemAttributeModifierEvent;)V
[21.09 09:14:33] [Server] java.lang.NullPointerExceptionCannot invoke "net.minecraft.world.entity.EquipmentSlot.equals(Object)" because the return value of "net.minecraftforge.event.ItemAttributeModifierEvent.getSlotType()" is null
[21.09 09:14:33] [Server] 	at TRANSFORMER/cnb@1.5.4/com.cgessinger.creaturesandbeasts.events.CNBEvents.onItemAttributeModifierCalculate(CNBEvents.java:90)
[21.09 09:14:33] [Server] 	at TRANSFORMER/cnb@1.5.4/com.cgessinger.creaturesandbeasts.events.__CNBEvents_onItemAttributeModifierCalculate_ItemAttributeModifierEvent.invoke(.dynamic)
[21.09 09:14:33] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[21.09 09:14:33] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[21.09 09:14:33] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[21.09 09:14:33] [Server] 	at TRANSFORMER/forge@43.2.21/net.minecraftforge.common.ForgeHooks.getAttributeModifiers(ForgeHooks.java:1111)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.m_41638_(ItemStack.java:909)
[21.09 09:14:33] [Server] 	at TRANSFORMER/aether@1.19.2-1.0.0-beta.1.1-forge/com.aetherteam.aether.event.hooks.AbilityHooks$WeaponHooks.reduceArmorEffectiveness(AbilityHooks.java:464)
[21.09 09:14:33] [Server] 	at TRANSFORMER/aether@1.19.2-1.0.0-beta.1.1-forge/com.aetherteam.aether.event.listeners.abilities.WeaponAbilityListener.onEntityDamage(WeaponAbilityListener.java:66)
[21.09 09:14:33] [Server] 	at TRANSFORMER/aether@1.19.2-1.0.0-beta.1.1-forge/com.aetherteam.aether.event.listeners.abilities.__WeaponAbilityListener_onEntityDamage_LivingDamageEvent.invoke(.dynamic)
[21.09 09:14:33] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[21.09 09:14:33] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[21.09 09:14:33] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[21.09 09:14:33] [Server] 	at TRANSFORMER/forge@43.2.21/net.minecraftforge.common.ForgeHooks.onLivingDamage(ForgeHooks.java:349)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.player.Player.m_6475_(Player.java:933)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1073)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.player.Player.m_6469_(Player.java:862)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerPlayer.m_6469_(ServerPlayer.java:671)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_7327_(Mob.java:1364)
[21.09 09:14:33] [Server] 	at TRANSFORMER/aether@1.19.2-1.0.0-beta.1.1-forge/com.aetherteam.aether.entity.monster.dungeon.boss.ValkyrieQueen.m_7327_(ValkyrieQueen.java:401)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.goal.MeleeAttackGoal.m_6739_(MeleeAttackGoal.java:147)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.goal.MeleeAttackGoal.m_8037_(MeleeAttackGoal.java:138)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_6140_(Mob.java:718)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2546)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_8107_(Mob.java:517)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2291)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_8119_(Mob.java:318)
[21.09 09:14:33] [Server] 	at TRANSFORMER/aether@1.19.2-1.0.0-beta.1.1-forge/com.aetherteam.aether.entity.monster.dungeon.AbstractValkyrie.m_8119_(AbstractValkyrie.java:85)
[21.09 09:14:33] [Server] 	at TRANSFORMER/aether@1.19.2-1.0.0-beta.1.1-forge/com.aetherteam.aether.entity.monster.dungeon.boss.ValkyrieQueen.m_8119_(ValkyrieQueen.java:162)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.mixinextras$bridge$accept$161(MixinLevel.java)
[21.09 09:14:33] [Server] 	at TRANSFORMER/neruina@1.2.1/com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:112)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.wrapOperation$bhk000$catchTickingEntities(MixinLevel.java:3038)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_46653_(MixinLevel.java:457)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
[21.09 09:14:33] [Server] 	at java.base/java.lang.Thread.run(Thread.java:833)
[21.09 09:14:33] [Server] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.world.entity.EquipmentSlot.equals(Object)" because the return value of "net.minecraftforge.event.ItemAttributeModifierEvent.getSlotType()" is null
[21.09 09:14:33] [Server] 	Index15
[21.09 09:14:33] [Server] 	Listeners:
[21.09 09:14:33] [Server] 		HIGHEST
[21.09 09:14:33] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$1586/0x0000000801384250@7c219275
[21.09 09:14:33] [Server] 		NORMAL
[21.09 09:14:33] [Server] 		ASM: insane96mcp.enhancedai.modules.spider.feature.Misc@5b92e89b onSpawn(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: class com.calculusmaster.difficultraids.entity.DREntityEvents onEntityDamaged(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: insane96mcp.enhancedai.modules.creeper.feature.CreeperSwell@bdd065f livingDamageEvent(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: class net.silentchaos512.gear.event.GearEvents onLivingDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: insane96mcp.progressivebosses.module.wither.feature.ResistancesFeature@25aacdcc onWitherDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: insane96mcp.progressivebosses.module.wither.feature.MinionFeature@717f45bd onMinionDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$1586/0x0000000801384250@537ffcce
[21.09 09:14:33] [Server] 		ASM: insane96mcp.progressivebosses.module.elderguardian.feature.ResistancesFeature@5eef94f7 onElderGuardianDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: insane96mcp.progressivebosses.module.dragon.feature.ResistancesFeature@7d6000e6 onDragonDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: insane96mcp.progressivebosses.module.dragon.feature.CrystalFeature@875768 onDragonDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@6d7cdd06 onLivingDamageEvent(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: class com.aetherteam.aether.item.combat.loot.FlamingSwordItem onLivingDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: class com.aetherteam.aether.event.listeners.abilities.WeaponAbilityListener onEntityDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: com.github.L_Ender.cataclysm.event.ServerEventHandler@cd5eb9e onLivingDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: class quek.undergarden.effect.BrittlenessEffect applyBrittleness(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: class com.obscuria.aquamirae.common.items.RuneOfTheStormItem onLivingDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: class io.redspace.ironsspellbooks.player.ServerPlayerEvents onLivingTakeDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: class io.redspace.ironsspellbooks.effect.BlightEffect reduceDamageOutput(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: class com.stal111.forbidden_arcanus.common.event.EntityEvents onEntityDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$1586/0x0000000801384250@1427f46f
[21.09 09:14:33] [Server] 		LOW
[21.09 09:14:33] [Server] 		ASM: com.aizistral.enigmaticlegacy.handlers.EnigmaticEventHandler@27af8e16 onEntityDamaged(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		LOWEST
[21.09 09:14:33] [Server] 		ASM: class ovh.corail.tombstone.event.EventHandler onPreventDeath(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		ASM: class com.sammy.malum.core.events.RuntimeEvents onLateDamage(Lnet/minecraftforge/event/entity/living/LivingDamageEvent;)V
[21.09 09:14:33] [Server] 		net.minecraftforge.eventbus.EventBus$$Lambda$1586/0x0000000801384250@ad99647
[21.09 09:14:33] [Server] java.lang.NullPointerExceptionCannot invoke "net.minecraft.world.entity.EquipmentSlot.equals(Object)" because the return value of "net.minecraftforge.event.ItemAttributeModifierEvent.getSlotType()" is null
[21.09 09:14:33] [Server] 	at TRANSFORMER/cnb@1.5.4/com.cgessinger.creaturesandbeasts.events.CNBEvents.onItemAttributeModifierCalculate(CNBEvents.java:90)
[21.09 09:14:33] [Server] 	at TRANSFORMER/cnb@1.5.4/com.cgessinger.creaturesandbeasts.events.__CNBEvents_onItemAttributeModifierCalculate_ItemAttributeModifierEvent.invoke(.dynamic)
[21.09 09:14:33] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
[21.09 09:14:33] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
[21.09 09:14:33] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
[21.09 09:14:33] [Server] 	at TRANSFORMER/forge@43.2.21/net.minecraftforge.common.ForgeHooks.getAttributeModifiers(ForgeHooks.java:1111)
[21.09 09:14:33] [Server] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.m_41638_(ItemStack.java:909)
[21.09 09:14:33] [Server] 	at TRANSFORMER/aether@1.19.2-1.0.0-beta.1.1-forge/com.aetherteam.aether.event.hooks.AbilityHooks$WeaponHooks.reduceArmorEffectiveness(AbilityHooks.java:464)
[21.09 09:14:33] [Server] 	at TRANSFORMER/aether@1.19.2-1.0.0-beta.1.1-forge/com.aetherteam.aether.event.listeners.abilities.WeaponAbilityListener.onEntityDamage(WeaponAbilityListener.java:66)
[21.09 09:14:33] [Server] 	at TRANSFORMER/aether@1.19.2-1.0.0-beta.1.1-forge/com.aetherteam.aether.event.listeners.abilities.__WeaponAbilityListener_onEntityDamage_LivingDamageEvent.invoke(.dynamic)
[21.09 09:14:33] [Server] 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by TioNickZeus** [comment]
i forgot to say, but im using a mod called "Neruina"
and i'm not native, so my english can by kind "bad"

**Comment by TioNickZeus** [comment]
update, i think this is hapening with every mob of the aether that hits de player

**Comment by bconlon1** [comment]
Report this to https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/issues, it seems to be an incompatibility and someone has run into it in the past. I'm not sure why it's going on so maybe their dev would have more insight.

**Comment by ajaxnotmeta** [comment]
also hapens with me using Aether alongside with Divine RPG and Curios or that was the mod i think adds new things about entity and slots
shouldi report this to DivineRPG team or something?
