### ISSUE TITLE
Bug: Few errors when "Use default Curios' menu" = true

### ISSUE THREAD

**Issue by Maypul** [Gilded-Games/The-Aether#1815]
### What Feature Types Apply to This Bug?

Config, Gui, System

### What Type of Bug Is This?

Annoyance

### Forge Version

43.2.21 / 1.19.2

### The Aether Version

1.0.0-beta.1.2-forge

### Is This Bug a Conflict With Another Mod?

Curios API / Corail Tombstone

### Steps to Reproduce

Errors happen when the "Use default Curios' menu" is set to true.

1. Install Curios API, Aether and change config "Use default Curios' menu" to true
2. Load Minecraft, create new world and login
3. Check logs and see following errors:
a) [17:55:49] [Render thread/ERROR] [minecraft/MultiPackResourceManager]: Failed to get filter section from pack aether-1.19.2-1.0.0-beta.1.2-forge.jar:packs/curios_tags
[17:55:50] [Render thread/ERROR] [minecraft/MultiPackResourceManager]: Failed to get filter section from pack aether-1.19.2-1.0.0-beta.1.2-forge.jar:packs/curios_tags

b) [17:57:32] [Server thread/ERROR] [minecraft/ServerFunctionLibrary]: Failed to load function aether:suit_up
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 10: Unknown curio slot type aether_gloves
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 10: Unknown curio slot type aether_gloves
	at net.minecraft.commands.CommandFunction.m_77984_(CommandFunction.java:63) ~[client-1.19.2-20220805.130853-srg.jar%23538!/:?] {re:classloading}
	at net.minecraft.server.ServerFunctionLibrary.m_214320_(ServerFunctionLibrary.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23538!/:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	... 6 more

a) Happens every time with just Curios + Aether
b) Happens only with addition of Corail Tombstone

### What You Expect To Happen

No errors in log.

### What Actually Happened

Errors in log.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Unless there are in-game issues, error logs aren't always a concern.
