### ISSUE TITLE
Bug: RP aether_colorblind causes an error in log with Fusion

### ISSUE THREAD

**Issue by Maypul** [Gilded-Games/The-Aether#1880]
### What Feature Types Apply to This Bug?

Config

### What Type of Bug Is This?

Annoyance

### Forge Version

43.2.21

### The Aether Version

1.0.0-beta2

### Is This Bug a Conflict With Another Mod?

Somewhat - Fusion 1.1.0b

### Client Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

1. Have Aether and Fusion installed
2. Run the game
3. Check logs and see that Aether's resource pack aether_colorblind causes a non critical and astetic error:

[20:49:36] [Render thread/ERROR] [fusion/]: Encountered an exception whilst reading fusion metadata for pack 'builtin/aether_colorblind':
java.io.FileNotFoundException: Can't find resource pack.mcmeta at packs/colorblind
	at net.minecraftforge.resource.PathPackResources.m_5541_(PathPackResources.java:112) ~[forge-1.19.2-43.2.21-universal.jar%23632!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.AbstractPackResources.m_5550_(AbstractPackResources.java:60) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.packs.repository.Pack.handler$bfh000$init(Pack.java:535) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.createClientPackAdapter(Minecraft.java:2771) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.aetherteam.aether.Aether.lambda$setupColorblindPack$22(Aether.java:308) ~[aether-1.19.2-1.0.0-beta.2-forge.jar%23396!/:1.19.2-1.0.0-beta.2-forge] {re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:47) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23150!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:66) [ForgeWrapper-1.5.7-prism.jar:1.5.7-prism] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}
[20:49:36] [Render thread/ERROR] [fusion/]: Encountered an exception whilst reading fusion metadata for pack 'builtin/aether_colorblind':
java.io.FileNotFoundException: Can't find resource pack.mcmeta at packs/colorblind
	at net.minecraftforge.resource.PathPackResources.m_5541_(PathPackResources.java:112) ~[forge-1.19.2-43.2.21-universal.jar%23632!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.AbstractPackResources.m_5550_(AbstractPackResources.java:60) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.packs.repository.Pack.handler$bfh000$init(Pack.java:535) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:79) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at fuzs.resourcepackoverrides.client.packs.repository.ForwardingPack.<init>(ForwardingPack.java:13) ~[ResourcePackOverrides-v4.0.4-1.19.2-Forge.jar%23588!/:4.0.4] {re:mixin,re:classloading}
	at fuzs.resourcepackoverrides.client.packs.repository.ForwardingPack.copy(ForwardingPack.java:18) ~[ResourcePackOverrides-v4.0.4-1.19.2-Forge.jar%23588!/:4.0.4] {re:mixin,re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.mda7bccf$lambda$discoverAvailable$0$0(PackRepository.java:525) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$6(CollectCollectors.java:184) ~[guava-31.0.1-jre.jar%23116!/:?] {}
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
	at net.minecraft.server.packs.repository.PackRepository.handler$zjc000$discoverAvailable(PackRepository.java:525) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:52) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23150!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:66) [ForgeWrapper-1.5.7-prism.jar:1.5.7-prism] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}

### What You Expect To Happen

No errors in logs

### What Actually Happened

Error in log:

[20:49:36] [Render thread/ERROR] [fusion/]: Encountered an exception whilst reading fusion metadata for pack 'builtin/aether_colorblind':
java.io.FileNotFoundException: Can't find resource pack.mcmeta at packs/colorblind
	at net.minecraftforge.resource.PathPackResources.m_5541_(PathPackResources.java:112) ~[forge-1.19.2-43.2.21-universal.jar%23632!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.AbstractPackResources.m_5550_(AbstractPackResources.java:60) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.packs.repository.Pack.handler$bfh000$init(Pack.java:535) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.createClientPackAdapter(Minecraft.java:2771) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.aetherteam.aether.Aether.lambda$setupColorblindPack$22(Aether.java:308) ~[aether-1.19.2-1.0.0-beta.2-forge.jar%23396!/:1.19.2-1.0.0-beta.2-forge] {re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:47) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23150!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:66) [ForgeWrapper-1.5.7-prism.jar:1.5.7-prism] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}
[20:49:36] [Render thread/ERROR] [fusion/]: Encountered an exception whilst reading fusion metadata for pack 'builtin/aether_colorblind':
java.io.FileNotFoundException: Can't find resource pack.mcmeta at packs/colorblind
	at net.minecraftforge.resource.PathPackResources.m_5541_(PathPackResources.java:112) ~[forge-1.19.2-43.2.21-universal.jar%23632!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.AbstractPackResources.m_5550_(AbstractPackResources.java:60) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.packs.repository.Pack.handler$bfh000$init(Pack.java:535) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:93) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.Pack.<init>(Pack.java:79) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:fusion.mixins.json:PackMixin,pl:mixin:APP:brrp-v1.mixins.json:ResourcePackProfileMixin,pl:mixin:APP:brrp-v1-forge.mixins.json:ResourcePackProfileForgeMixin,pl:mixin:A}
	at fuzs.resourcepackoverrides.client.packs.repository.ForwardingPack.<init>(ForwardingPack.java:13) ~[ResourcePackOverrides-v4.0.4-1.19.2-Forge.jar%23588!/:4.0.4] {re:mixin,re:classloading}
	at fuzs.resourcepackoverrides.client.packs.repository.ForwardingPack.copy(ForwardingPack.java:18) ~[ResourcePackOverrides-v4.0.4-1.19.2-Forge.jar%23588!/:4.0.4] {re:mixin,re:classloading}
	at net.minecraft.server.packs.repository.PackRepository.mda7bccf$lambda$discoverAvailable$0$0(PackRepository.java:525) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$6(CollectCollectors.java:184) ~[guava-31.0.1-jre.jar%23116!/:?] {}
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
	at net.minecraft.server.packs.repository.PackRepository.handler$zjc000$discoverAvailable(PackRepository.java:525) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.PackRepository.m_10526_(PackRepository.java:52) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at net.minecraft.server.packs.repository.PackRepository.m_10506_(PackRepository.java:39) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:resourcepackoverrides.common.mixins.json:client.PackRepositoryMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23150!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:66) [ForgeWrapper-1.5.7-prism.jar:1.5.7-prism] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}

### Additional Details

N/A

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
You should probably report this to Fusion, it seems like they may not read built-in resource packs correctly.
