### ISSUE TITLE
Bug: Recipe mistake with JER, causing a very very long console error

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Gilded-Games/The-Aether#1897]
### What Feature Types Apply to This Bug?

Item, System, Other (Please Describe)

### Other Type

Item API issue

### What Type of Bug Is This?

`Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: jeresources.jei.mob.MobWrapper@4d561c00`

`Cannot invoke "com.aetherteam.aether.api.registers.MoaType.getId()" because "moaType" is null`

### Forge Version

47.2.0

### The Aether Version

aether-1.20.1-1.0.0-neoforge.jar

### Is This Bug a Conflict With Another Mod?

Yes/partially

### Client Log

https://api.paste.ee/p/Ls4Hy

### Steps to Reproduce

- Install aether-1.20.1-1.0.0-neoforge.jar
- Install JustEnoughResources-1.20.1-1.4.0.238.jar
- Launch MC
- The error will be on the console, and JER will likely be affected on that item (moa egg)

### What You Expect To Happen

No error on the console, my console is clean and beautifu

### What Actually Happened

[04:53:43] [Render thread/ERROR] [me.je.li.ut.IngredientSupplierHelper/]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: jeresources.jei.mob.MobWrapper@4d561c00

java.lang.NullPointerException: Cannot invoke "com.aetherteam.aether.api.registers.MoaType.getId()" because "moaType" is null
	at com.aetherteam.aether.item.miscellaneous.MoaEggItem.byId(MoaEggItem.java:192) ~[aether-1.20.1-1.0.0-neoforge.jar%23246!/:1.20.1-1.0.0-neoforge] {re:classloading}
	at com.aetherteam.aether.entity.passive.Moa.m_142340_(Moa.java:850) ~[aether-1.20.1-1.0.0-neoforge.jar%23246!/:1.20.1-1.0.0-neoforge] {re:classloading}
	at jeresources.jei.mob.MobWrapper.getSpawnEgg(MobWrapper.java:160) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23307!/:1.4.0.238] {re:classloading}
	at jeresources.jei.mob.MobWrapper.hasSpawnEgg(MobWrapper.java:156) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23307!/:1.4.0.238] {re:classloading}
	at jeresources.jei.mob.MobCategory.setRecipe(MobCategory.java:63) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23307!/:1.4.0.238] {re:classloading}
	at jeresources.jei.mob.MobCategory.setRecipe(MobCategory.java:19) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23307!/:1.4.0.238] {re:classloading}
	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at mezz.jei.library.recipes.RecipeManagerInternal.lambda$addRecipes$0(RecipeManagerInternal.java:120) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?] {}
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:126) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:108) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at mezz.jei.library.load.registration.RecipeRegistration.addRecipes(RecipeRegistration.java:64) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at jeresources.jei.JEIConfig.registerRecipes(JEIConfig.java:75) ~[JustEnoughResources-1.20.1-1.4.0.238.jar%23307!/:1.4.0.238] {re:classloading}
	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$10(PluginLoader.java:144) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:144) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:132) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.20.1-forge-15.2.0.27.jar%23305!/:15.2.0.27] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_close,xf:fml:xaerominimap:xaero_clientplaynethandler_close,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_updatelevelchunk,xf:fml:xaerominimap:xaero_clientplaynethandler_updatelevelchunk,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_queuelightremoval,xf:fml:xaerominimap:xaero_clientplaynethandler_queuelightremoval,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaeroworldmap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelightupdatepacket,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelightupdatepacket,xf:fml:xaerominimap:xaero_clientlistener_sendcommand,xf:fml:xaerominimap:xaero_clientlistener_commandunsigned,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandlerclass,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_close,xf:fml:xaerominimap:xaero_clientplaynethandler_close,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_updatelevelchunk,xf:fml:xaerominimap:xaero_clientplaynethandler_updatelevelchunk,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_queuelightremoval,xf:fml:xaerominimap:xaero_clientplaynethandler_queuelightremoval,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaeroworldmap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelightupdatepacket,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelightupdatepacket,xf:fml:xaerominimap:xaero_clientlistener_sendcommand,xf:fml:xaerominimap:xaero_clientlistener_commandunsigned,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandlerclass,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,pl:mixin:APP:aether.mixins.json:client.ClientPacketListenerMixin,pl:mixin:APP:naturalist-common.mixins.json:ClientPacketListenerMixin,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientPlayNetworkHandlerMixin,pl:mixin:APP:crafttweaker.mixins.json:client.transform.multiplayer.MixinClientPacketListener,pl:mixin:APP:friendsandfoes-common.mixins.json:ClientPlayNetworkHandlerMixin,pl:mixin:APP:alexscaves.mixins.json:client.ClientPacketListenerMixin,pl:mixin:APP:flywheel.mixins.json:light.NetworkLightUpdateMixin,pl:mixin:APP:starlight.mixins.json:client.multiplayer.ClientPacketListenerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23360!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[?:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[?:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[?:?] {}

### Additional Details

I was so hopeful that going from beta 1.4 to the release would fix it, but it didn't. That error on my console is slowly driving me bald every time I have to scroll through it for some other reason. It's a pretty minor API error but the console spam is horrible

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
While it may be unrelated, you should be using 47.1.3 instead of 47.2.0.
