### ISSUE TITLE
Bug: <title>

### ISSUE THREAD

**Issue by lSherozl** [Gilded-Games/The-Aether#2015]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### What Type of Bug Is This?

None

### Forge Version

43.3.5

### The Aether Version

1.0.0-beta.1.3

### Is This Bug a Conflict With Another Mod?

Possibly

### Steps to Reproduce

 Only the top part focuses on aether, I'm wondering if its a issue with a resource or datapack or normal for the mod: packs/ctm_fix

[02:29:43] [Render thread/ERROR]: Failed to get filter section from pack aether-1.19.2-1.0.0-beta.1.3-forge.jar:packs/ctm_fix
[02:29:43] [Render thread/WARN]: Failed to find texture for Leaf Pile Block{immersive_weathering:twilightforest/beanstalk_leaf_pile}, using oak one instead
[02:29:43] [Render thread/WARN]: Failed to find texture for Leaf Pile Block{immersive_weathering:twilightforest/thorn_leaf_pile}, using oak one instead
[02:29:43] [Render thread/ERROR]: Fail to generate Leaf Particle texture for type twilightforest:beanstalk : java.io.FileNotFoundException: Could not find any texture associated to the given block twilightforest:beanstalk_leaves
[02:29:43] [Render thread/ERROR]: Fail to generate Leaf Particle texture for type twilightforest:thorn : java.io.FileNotFoundException: Could not find any texture associated to the given block twilightforest:thorn_leaves
[02:29:43] [Render thread/ERROR]: Could not generate heavy leaf pile texture for type twilightforest:beanstalk
java.io.FileNotFoundException: Could not find any texture associated to the given block twilightforest:beanstalk_leaves
	at net.mehvahdjukaar.moonlight.api.resources.RPUtils.findFirstBlockTextureLocation(RPUtils.java:100) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.RPUtils.findFirstBlockTextureLocation(RPUtils.java:58) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at com.ordana.immersive_weathering.dynamicpack.ClientDynamicResourcesHandler.lambda$regenerateDynamicAssets$6(ClientDynamicResourcesHandler.java:232) ~[immersive_weathering-1.19.2-1.2.10-forge.jar%23866!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at com.ordana.immersive_weathering.dynamicpack.ClientDynamicResourcesHandler.regenerateDynamicAssets(ClientDynamicResourcesHandler.java:227) ~[immersive_weathering-1.19.2-1.2.10-forge.jar%23866!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.reloadResources(DynResourceProvider.java:115) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.onEarlyReload(DynResourceProvider.java:83) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.events.forge.MoonlightEventsHelperImpl.lambda$postEvent$5(MoonlightEventsHelperImpl.java:43) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.forge.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:43) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.handler$hma000$dynamicPackEarlyReload(MultiPackResourceManager.java:2534) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.<init>(MultiPackResourceManager.java:61) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:44) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:577) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[02:29:43] [Render thread/ERROR]: Could not generate heavy leaf pile texture for type twilightforest:thorn
java.io.FileNotFoundException: Could not find any texture associated to the given block twilightforest:thorn_leaves
	at net.mehvahdjukaar.moonlight.api.resources.RPUtils.findFirstBlockTextureLocation(RPUtils.java:100) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.RPUtils.findFirstBlockTextureLocation(RPUtils.java:58) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at com.ordana.immersive_weathering.dynamicpack.ClientDynamicResourcesHandler.lambda$regenerateDynamicAssets$6(ClientDynamicResourcesHandler.java:232) ~[immersive_weathering-1.19.2-1.2.10-forge.jar%23866!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at com.ordana.immersive_weathering.dynamicpack.ClientDynamicResourcesHandler.regenerateDynamicAssets(ClientDynamicResourcesHandler.java:227) ~[immersive_weathering-1.19.2-1.2.10-forge.jar%23866!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.reloadResources(DynResourceProvider.java:115) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.onEarlyReload(DynResourceProvider.java:83) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.events.forge.MoonlightEventsHelperImpl.lambda$postEvent$5(MoonlightEventsHelperImpl.java:43) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.forge.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:43) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.handler$hma000$dynamicPackEarlyReload(MultiPackResourceManager.java:2534) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.<init>(MultiPackResourceManager.java:61) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:44) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:577) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[02:29:43] [Render thread/INFO]: Generated runtime CLIENT_RESOURCES for pack Immersive Weathering Generated Pack in: 175 ms
[02:29:44] [Render thread/WARN]: failed to apply azalea overlay: 
java.lang.IllegalStateException: Could not merge images because they had different dimensions
	at net.mehvahdjukaar.moonlight.api.resources.textures.TextureImage.applyOverlayOnExisting(TextureImage.java:294) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.every_compat.api.CompatModule.maybeFlowerAzalea(CompatModule.java:209) ~[everycomp-1.19.2-2.5.14.jar%23806!/:?]
	at net.mehvahdjukaar.every_compat.api.CompatModule.lambda$addWoodTexture$0(CompatModule.java:191) ~[everycomp-1.19.2-2.5.14.jar%23806!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynClientResourcesProvider.addTextureIfNotPresent(DynClientResourcesProvider.java:61) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.every_compat.api.CompatModule.addWoodTexture(CompatModule.java:189) ~[everycomp-1.19.2-2.5.14.jar%23806!/:?]
	at net.mehvahdjukaar.every_compat.api.AbstractSimpleEntrySet.generateTextures(AbstractSimpleEntrySet.java:236) ~[everycomp-1.19.2-2.5.14.jar%23806!/:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.lambda$addDynamicClientResources$9(SimpleModule.java:99) ~[everycomp-1.19.2-2.5.14.jar%23806!/:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at net.mehvahdjukaar.every_compat.api.SimpleModule.addDynamicClientResources(SimpleModule.java:99) ~[everycomp-1.19.2-2.5.14.jar%23806!/:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ClientDynamicResourcesHandler.lambda$regenerateDynamicAssets$1(ClientDynamicResourcesHandler.java:45) ~[everycomp-1.19.2-2.5.14.jar%23806!/:?]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.forAllModules(EveryCompat.java:80) ~[everycomp-1.19.2-2.5.14.jar%23806!/:?]
	at net.mehvahdjukaar.every_compat.dynamicpack.ClientDynamicResourcesHandler.regenerateDynamicAssets(ClientDynamicResourcesHandler.java:43) ~[everycomp-1.19.2-2.5.14.jar%23806!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.reloadResources(DynResourceProvider.java:115) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.resources.pack.DynResourceProvider.onEarlyReload(DynResourceProvider.java:83) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.events.forge.MoonlightEventsHelperImpl.lambda$postEvent$5(MoonlightEventsHelperImpl.java:43) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?]
	at net.mehvahdjukaar.moonlight.api.events.forge.MoonlightEventsHelperImpl.postEvent(MoonlightEventsHelperImpl.java:43) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.mehvahdjukaar.moonlight.api.events.MoonlightEventsHelper.postEvent(MoonlightEventsHelper.java) ~[moonlight-1.19.2-2.3.5-forge.jar%23920!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.handler$hma000$dynamicPackEarlyReload(MultiPackResourceManager.java:2534) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.server.packs.resources.MultiPackResourceManager.<init>(MultiPackResourceManager.java:61) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.server.packs.resources.ReloadableResourceManager.m_142463_(ReloadableResourceManager.java:44) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:577) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%231116!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[02:29:45] [Render thread/ERROR]: Failed to generate texture everycomp:block/ch/phantasm/ebony_planks/brick_bond_oak_planks: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1

### What You Expect To Happen

None of this causes a crash, just an error I noticed in my log

### What Actually Happened

None of this causes a crash, just an error I noticed in my log

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Forge had some odd errors in 1.19.2 relating to resources and data. It doesn't appear to be causing issues so it should be fine. Also unrelated, but you should probably be using a release build now instead of an old beta.
