### ISSUE TITLE
Bug: Running into error when trying to install to NeoForge Mod folder in linux

### ISSUE THREAD

**Issue by EthanGaspar** [Gilded-Games/The-Aether#2076]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Design

### Forge Version

NeoForge 20.2.88

### The Aether Version

1.20.2

### Steps to Reproduce

I created a Google Cloud VM to host server following steps in link :
https://www.youtube.com/watch?v=1G8LIwuEiTU&t=370s
However it just stores the files of the NeoForge Server.
within mods folder of the NeoForge file I(to start the server):
1.) download mod using wget https://cdn.modrinth.com/data/YhmgMVyu/versions/YamjzGxS/aether-1.20.2-1.3.1-neoforge.jar
2.)chmod +x run.sh
3.) /run.sh

### What You Expect To Happen

I expected the server to open as normal with the mod

### What Actually Happened

Terminal ran into error surrounding due to cumulus_menus:menu not being loaded properly
**Error here**:

[03:38:01] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
java.lang.IllegalStateException: The following registries were created but not registered to NewRegistryEvent:
         - cumulus_menus:menu
        at net.neoforged.neoforge.registries.RegistryManager.postNewRegistryEvent(RegistryManager.java:68) ~[neoforge-20.2.88-universal.jar%23130!/:?] {re:classloading}
        at net.neoforged.neoforge.internal.NeoForgeStatesProvider.lambda$new$0(NeoForgeStatesProvider.java:19) ~[neoforge-20.2.88-universal.jar%23130!/:?] {re:classloading}
        at net.neoforged.fml.ModLoader.handleInlineTransition(ModLoader.java:220) ~[core-1.0.16.jar%23126!/:1.0] {}
        at net.neoforged.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:212) ~[core-1.0.16.jar%23126!/:1.0] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
        at net.neoforged.fml.ModLoader.dispatchAndHandleError(ModLoader.java:212) ~[core-1.0.16.jar%23126!/:1.0] {}
        at net.neoforged.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:186) ~[core-1.0.16.jar%23126!/:1.0] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
        at net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:186) ~[core-1.0.16.jar%23126!/:1.0] {}
        at net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:28) ~[neoforge-20.2.88-universal.jar%23130!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:122) ~[server-1.20.2-20231019.002635-srg.jar%23125!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-1.0.16.jar%2362!/:1.0] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:118) ~[loader-1.0.16.jar%2362!/:1.0] {}
        at net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:26) ~[loader-1.0.16.jar%2362!/:1.0] {}
        at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-1.0.16.jar%2362!/:1.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2365!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

### Additional Details

Im pretty new to minecraft modding and linux, so Im not sure if the issue is with the mod or the server. Since the mod works fine when I install it locally. Thanks again

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Will be fixed with 1.20.2-1.3.2.
