### ISSUE TITLE
Bug: Issue on request interface com.aetherteam.aetherfabric.pond.IRegistryExtension

### ISSUE THREAD

**Issue by suerion** [Gilded-Games/The-Aether#2382]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Crash

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

aether-1.21.1-1.5.1-beta.4-fabric

### Is This Bug a Conflict With Another Mod?

Don't know yet

### Client Log

Warning on Datapacks: https://mclo.gs/qorkWQ8

### Steps to Reproduce

Add Aether on a Huge Modpack Server and try to start on clean modpack, (Mods, config, no world)

### What You Expect To Happen

Generate world with datapacks 

it has worked a few times, but this time there is the issue

### What Actually Happened

Server Stop on Startup

### Additional Details

latest server log:
https://mclo.gs/HrF8XJq

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Can you try removing farmersdelight and relaunching as I might have a hunch to what is occuring

**Comment by suerion** [comment]
Will try and come back with update

**Comment by suerion** [comment]
Had disabled Farmers Delight and all addons from it, here is the issue persistend,

https://mclo.gs/ZU2weFh

**Comment by Dragon-Seeker** [comment]
Hmm ok, can you next try removing automodpack temporarily. If such persists it will requires some investigation why this occurs as this shouldn't be happening

**Comment by suerion** [comment]
Will try it tomorow, automodpack does only make mess on client side, Because it load mixin 4.1 and not the beta mixin, what cause the mixin Injektion problems.

I'm work on debuging the issue and tomorow should be come a new automodpack update. 

But i will try more tests after work tomorow

**Comment by suerion** [comment]
@Dragon-Seeker had disabled also Automodpack, but the error occurs again. Will look on other mods, but i don't know, what coult be the issue here, had no problems before

https://mclo.gs/qrlsZjw

**Comment by suerion** [comment]
oh wait, had not seen this issue  before ->

```
Mod aether provides a broken MixinCanceller implementation:
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'mixinsquared' provided by 'aether'
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
        at knot//com.bawnorton.mixinsquared.platform.fabric.MixinSquaredApiImplLoader.lambda$load$0(MixinSquaredApiImplLoader.java:38)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at knot//com.bawnorton.mixinsquared.platform.fabric.MixinSquaredApiImplLoader.load(MixinSquaredApiImplLoader.java:35)
        at knot//com.bawnorton.mixinsquared.platform.fabric.MixinSquaredMixinConfigPlugin.onLoad(MixinSquaredMixinConfigPlugin.java:40)
        at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:790)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: com.aetherteam.aetherfabric.AetherFabricMixinCanceller
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52)
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
        ... 29 more
Caused by: java.lang.ClassNotFoundException: com.aetherteam.aetherfabric.AetherFabricMixinCanceller
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
        ... 31 more
```

**Comment by suerion** [comment]
Tested on Windows 11, same issue, had added again all mods
https://mclo.gs/YNrPuDq

**Comment by suerion** [comment]
@Dragon-Seeker if you had an build to test, i could test it on my enviroment ;)

**Comment by Dragon-Seeker** [comment]
Ill see about getting you one later today/tomorrow (Time zones are fun).

**Comment by suerion** [comment]
Time zones are really fun, here it is 09:00 am

**Comment by suerion** [comment]
@Dragon-Seeker did you found something about this issue?

**Comment by suerion** [comment]
Got a new Issue 
```
[17:21:55 WARN] [main]: [Main] Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IncompatibleClassChangeError: Class net.minecraft.class_2348 does not implement the requested interface com.aetherteam.aetherfabric.pond.IRegistryExtension
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at knot/net.minecraft.server.Main.main(Main.java:229) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.IncompatibleClassChangeError: Class net.minecraft.class_2348 does not implement the requested interface com.aetherteam.aetherfabric.pond.IRegistryExtension
        at knot/com.aetherteam.aetherfabric.AetherFabric$FurnaceFuelCallback.lambda$onUpdate$2(AetherFabric.java:105) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.registries.datamaps.DataMapsUpdatedEvent.ifRegistry(DataMapsUpdatedEvent.java:67) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.AetherFabric$FurnaceFuelCallback.onUpdate(AetherFabric.java:104) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.registries.datamaps.DataMapsUpdatedEvent.lambda$static$0(DataMapsUpdatedEvent.java:22) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.registries.DataMapLoader.apply(DataMapLoader.java:67) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.registries.DataMapLoader.lambda$apply$1(DataMapLoader.java:56) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at knot/com.aetherteam.aetherfabric.registries.DataMapLoader.apply(DataMapLoader.java:56) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.AetherFabric.lambda$init$4(AetherFabric.java:85) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/net.fabricmc.fabric.api.event.lifecycle.v1.CommonLifecycleEvents.lambda$static$0(CommonLifecycleEvents.java:33) ~[fabric-lifecycle-events-v1-2.5.0+01d9a51c19-8ff401bae2cee6b0.jar:?]
        at knot/net.minecraft.server.ReloadableServerResources.handler$dka000$fabric-lifecycle-events-v1$hookRefresh(ReloadableServerResources.java:3039) ~[?:?]
        at knot/net.minecraft.server.ReloadableServerResources.updateRegistryTags(ReloadableServerResources.java:94) ~[?:?]
        at knot/net.minecraft.server.WorldLoader.lambda$load$1(WorldLoader.java:52) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at knot/net.minecraft.Util.blockUntilDone(Util.java:1024) ~[?:?]
        at knot/net.minecraft.Util.blockUntilDone(Util.java:1012) ~[?:?]
        at knot/net.minecraft.server.Main.main(Main.java:182) ~[server-intermediary.jar:?]
        ... 5 more
```

**Comment by Dragon-Seeker** [comment]
Sorry for the delay on this but I don't exactly know how to send a prerelease build that may fix the issue and some Cumulus rewrite stuff has gotten a bit staled but hopefully such can be dealt with soon.

**Comment by suerion** [comment]
@Dragon-Seeker if you had an commit, that finished it, or an pull request, that should be fixed it, you could send me the link there, then i could buid it for me  with gradle

**Comment by Dragon-Seeker** [comment]
@suerion Try this build: https://output.circle-artifacts.com/output/job/ba4b3475-ae14-41de-b8a3-7bea94d8c54f/artifacts/0/~/project/build/libs/aether-1.21.1-1.5.1-beta.4-fabric.jar

**Comment by suerion** [comment]
would test the build tomorow, got no time this weekend.

**Comment by suerion** [comment]
same issue again 

```
[23:15:53 WARN] [main]: [Main] Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IncompatibleClassChangeError: Class net.minecraft.class_2348 does not implement the requested interface com.aetherteam.aetherfabric.pond.IRegistryExtension
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at knot/net.minecraft.server.Main.main(Main.java:229) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.IncompatibleClassChangeError: Class net.minecraft.class_2348 does not implement the requested interface com.aetherteam.aetherfabric.pond.IRegistryExtension
        at knot/com.aetherteam.aetherfabric.AetherFabric$FurnaceFuelCallback.lambda$onUpdate$2(AetherFabric.java:105) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.registries.datamaps.DataMapsUpdatedEvent.ifRegistry(DataMapsUpdatedEvent.java:67) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.AetherFabric$FurnaceFuelCallback.onUpdate(AetherFabric.java:104) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.registries.datamaps.DataMapsUpdatedEvent.lambda$static$0(DataMapsUpdatedEvent.java:22) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.registries.DataMapLoader.apply(DataMapLoader.java:67) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.registries.DataMapLoader.lambda$apply$1(DataMapLoader.java:56) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at knot/com.aetherteam.aetherfabric.registries.DataMapLoader.apply(DataMapLoader.java:56) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/com.aetherteam.aetherfabric.AetherFabric.lambda$init$4(AetherFabric.java:85) ~[aether-1.21.1-1.5.1-beta.4-fabric.jar:?]
        at knot/net.fabricmc.fabric.api.event.lifecycle.v1.CommonLifecycleEvents.lambda$static$0(CommonLifecycleEvents.java:33) ~[fabric-lifecycle-events-v1-2.5.0+01d9a51c19-8ff401bae2cee6b0.jar:?]
        at knot/net.minecraft.server.ReloadableServerResources.handler$din000$fabric-lifecycle-events-v1$hookRefresh(ReloadableServerResources.java:3039) ~[?:?]
        at knot/net.minecraft.server.ReloadableServerResources.updateRegistryTags(ReloadableServerResources.java:94) ~[?:?]
        at knot/net.minecraft.server.WorldLoader.lambda$load$1(WorldLoader.java:52) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at knot/net.minecraft.Util.blockUntilDone(Util.java:1024) ~[?:?]
        at knot/net.minecraft.Util.blockUntilDone(Util.java:1012) ~[?:?]
        at knot/net.minecraft.server.Main.main(Main.java:182) ~[server-intermediary.jar:?]
        ... 5 more
```

**Comment by Dragon-Seeker** [comment]
@suerion Can you send the latest full log?

**Comment by suerion** [comment]
yeah, @Dragon-Seeker here you get it ->

https://mclo.gs/Lobz7wD

**Comment by Dragon-Seeker** [comment]
Hmmm something about this pack seems to conflicting with Aether some how and I don't know what exactly

**Comment by suerion** [comment]
Had tried to disable all mods and get allways the same issue of the iregistry, could try again to disable all. 
 
But it takes time, will come back again.

**Comment by suerion** [comment]
had only looked there fore the class -> https://maven.fabricmc.net/docs/yarn-1.21.1+build.3/net/minecraft/registry/SimpleDefaultedRegistry.html

could it be a help?

**Comment by suerion** [comment]
https://github.com/The-Aether-Team/The-Aether/blob/1.21.1-1.5.1-beta.5-fabric/src/main/java/com/aetherteam/aetherfabric/pond/IRegistryExtension.java

**Comment by Dragon-Seeker** [comment]
@suerion I understand the classes that are involved but I believe you need to binary search your modpack for conflicting mod(s) to figure this out as it is 700 mod pack and by itself the aether dose not have this issue in prod or dev

**Comment by suerion** [comment]
Will check in the next few days the pack, to find any mods

**Comment by suerion** [comment]
@Dragon-Seeker had found the Culprit... pruhhh

https://mclo.gs/ZY4qn5J

https://modrinth.com/mod/serilums-spawn-bundle

**Comment by suerion** [comment]
need to seperate the mods, will come back with the issuer

**Comment by James103** [comment]
The conflicting mod (Serilum's Spawn Bundle) is actually a bundle of several mods; can you please bisect through the following possible conflicting mods to further narrow down the cause?
```
boggedspawn 1.1
breezespawn 1.1
cavespiderspawn 1.2
giantspawn 5.2
huskspawn 3.6
mooshroomspawn 3.6
mooshroomtweaks 3.5
morezombievillagers 3.6
skeletonhorsespawn 4.0
strayspawn 3.7
zombiehorsespawn 5.1
zombievillagersfromspawner 3.9
```

**Comment by suerion** [comment]
> The conflicting mod (Serilum's Spawn Bundle) is actually a bundle of several mods; can you please bisect through the following possible conflicting mods to further narrow down the cause?
> 
> ```
> boggedspawn 1.1
> breezespawn 1.1
> cavespiderspawn 1.2
> giantspawn 5.2
> huskspawn 3.6
> mooshroomspawn 3.6
> mooshroomtweaks 3.5
> morezombievillagers 3.6
> skeletonhorsespawn 4.0
> strayspawn 3.7
> zombiehorsespawn 5.1
> zombievillagersfromspawner 3.9
> ```

@James103  @Dragon-Seeker it has nothing to do with the Mods itself, i think it is only the bundle himself

https://mclo.gs/PQM6Xiv

**Comment by suerion** [comment]
Workaround, only use the mods alone and not in the bundle, the fabric loader has issues to work with jar in jar files.
