### ISSUE TITLE
Crash When Starting Client

### ISSUE THREAD

**Issue by duplexsystem** [Gilded-Games/The-Aether#25]
Thread: Render thread
Stacktrace:
	at com.aether.client.renderer.AetherAtlases.getChestMaterial(AetherAtlases.java:22) ~[?:1.16.4-v1.5.0] {re:classloading,pl:runtimedistcleaner:A}
-- MOD aether --
Details:
	Mod File: aether-1.16.4-v1.5.0.jar
	Failure message: The Aether (aether) has failed to load correctly
		java.lang.NoSuchFieldError: CHEST_ATLAS
	Mod Version: 1.16.4-v1.5.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchFieldError: CHEST_ATLAS
Stacktrace:
	at com.aether.client.renderer.AetherAtlases.getChestMaterial(AetherAtlases.java:22) ~[?:1.16.4-v1.5.0] {re:classloading,pl:runtimedistcleaner:A}
	at com.aether.client.renderer.AetherAtlases.<clinit>(AetherAtlases.java:17) ~[?:1.16.4-v1.5.0] {re:classloading,pl:runtimedistcleaner:A}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.AutomaticEventSubscriber$$Lambda$3171/2132532344.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[?:35.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3085/835631769.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3109/1799521220.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

Only Mods are Aether and Curios.

**Comment by Burning-Cactus** [comment]
This crash was caused by a faulty jar of the mod. Mods can only be built with ./gradlew build, not ./gradlew jar.
